# Generated by Django 4.2.30 on 2026-09-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='payment_method',
            field=models.CharField(choices=[('Offline', 'Offline'), ('bKash', 'bKash'), ('Nagad', 'Nagad')], default='Offline', max_length=20),
        ),
    ]
