# Generated by Django 4.2.30 on 2026-07-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_waitlistentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text='e.g. University Student, Avid Reader', max_length=100)),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating from 1 to 5')),
                ('review_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Testimonial',
                'verbose_name_plural': 'Site Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
