# Generated by Django 4.2.30 on 2026-07-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_sitetestimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='wafilife_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manually enter the price of this book on Wafilife (Optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='wafilife_url',
            field=models.URLField(blank=True, help_text='Direct link to this book on Wafilife (Optional)'),
        ),
    ]
