# Generated by Django 4.2.30 on 2026-07-17 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_book_wafilife_price_book_wafilife_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who made the request (if logged in)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
