# Generated by Django 4.2.30 on 2026-07-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_bookrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='default_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default discount % applied to new books from this publication (0–100)', max_digits=5),
        ),
    ]
