# Generated by Django 4.2.30 on 2026-10-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_publication_default_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='barcode',
            field=models.CharField(blank=True, help_text='EAN-13 Barcode', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='low_stock_threshold',
            field=models.IntegerField(default=5, help_text='Alert when stock falls below this number'),
        ),
    ]
