# Generated by Django 4.2.30 on 2026-07-12 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('Buy', 'Buy'), ('Borrow', 'Borrow')], default='Buy', max_length=10)),
                ('delivery_option', models.CharField(choices=[('free_chawkbazar', 'Free Delivery — Chawkbazar'), ('free_2no_gate', 'Free Delivery — 2 No Gate'), ('free_hathazari', 'Free Delivery — Hathazari'), ('free_cuet', 'Free Delivery — CUET'), ('offline_store', 'Offline Store Pickup'), ('inside_ctg', 'Home Delivery Inside CTG'), ('outside_ctg', 'Home Delivery Outside CTG')], max_length=30)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('book_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Offline', 'Offline / Cash on Delivery'), ('bKash', 'bKash')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, help_text='Return due date for borrows', null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
