# Generated by Django 4.2.30 on 2026-07-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_bill_number_order_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='group_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
