# Generated by Django 4.2.30 on 2026-07-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_group_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('free_kazir_dewri', 'Free Delivery — Kazir Dewri'), ('free_2no_gate', 'Free Delivery — 2 No Gate'), ('free_hathazari', 'Free Delivery — Hathazari'), ('free_cuet', 'Free Delivery — CUET'), ('offline_store', 'Offline Store Pickup'), ('inside_ctg', 'Home Delivery Inside CTG'), ('outside_ctg', 'Home Delivery Outside CTG')], max_length=30),
        ),
    ]
