# Generated by Django 4.2.30 on 2026-07-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_delivery_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Free Delivery — Kazir Dewri', max_length=150, unique=True)),
                ('code', models.SlugField(help_text='Unique lowercase identifier (e.g. free_kazir_dewri)', max_length=100, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee (0.00 for free delivery)', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this option is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Delivery Option',
                'verbose_name_plural': 'Delivery Options',
                'ordering': ['cost', 'label'],
            },
        ),
    ]
