# Generated by Django 4.2.30 on 2026-09-15 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_delivery_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinebill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
