# Generated by Django 4.2.30 on 2026-09-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_offlinebill_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Offline', 'Offline / Cash on Delivery'), ('bKash', 'bKash'), ('Nagad', 'Nagad')], max_length=20),
        ),
    ]
