# Generated by Django 4.2.30 on 2026-10-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinebill',
            name='cash_tendered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='offlinebill',
            name='change_returned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
